from_latest_tag = true
disable_changelog = true

ignore_merge_commits = false
ignore_fixup_commits = true

disable_bump_commit = false

branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false

tag_prefix = "v"

pre_bump_hooks = [
  "cargo build --release",
  "cargo set-version {{version}}",
]
post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
]

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e
cargo fmt -v --all --check
cargo clippy
"""
